### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by zhombie** [SevereCloud/vk-streaming#4]
Как можно переподключиться на вебсокет при падении?

при вызове,
response = await session.get('https' + url, headers=headers)
вылетает ошибка пока с ответом Bad Request

**Comment by SevereCloud** [comment]
Не очень понял причем тут асинхронность и данный модуль

**Comment by zhombie** [comment]
Ведь вы же сами написали здесь процесс переподключения: https://github.com/SevereCloud/vk-streaming/blob/99033c99deabbd5f3199fa613b9ab9357ef78138/vkstreaming/core.py#L187-L200

но иногда при запросе 
`requests.get("https" + url, headers=headers, proxies=self.proxies)`
получаю: **Bad Request**

теперь мой вопрос, как можно улучшить данный процесс переподключения?
